package com.core.ui.utils

//DELAYS
const val DELAY_TIME_2000 = 2000L
const val DELAY_TIME_1000 = 1000L
const val DELAY_TIME_166 = 166L
const val DELAY_TIME_100 = 100L

//GENERAL
const val SPLASH_ANIMATION_SIZE = 8

//ANIMATIONS OFFSETS
const val SLIDE_IN_OFFSET_START = 0
const val SLIDE_IN_OFFSET_END = 1000

//CARD SIZES
const val SCREEN_HEIGHT_DIVIDER = 6
const val SCREEN_WIDTH_DIVIDER = 2
